//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchView.Properties.Resource_en-US", typeof(Resource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string ddlCroatian {
            get {
                return ResourceManager.GetString("ddlCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ddlEnglish {
            get {
                return ResourceManager.GetString("ddlEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string ddlFemale {
            get {
                return ResourceManager.GetString("ddlFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string ddlFullscreen {
            get {
                return ResourceManager.GetString("ddlFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string ddlGerman {
            get {
                return ResourceManager.GetString("ddlGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string ddlMale {
            get {
                return ResourceManager.GetString("ddlMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string ddlOriginal {
            get {
                return ResourceManager.GetString("ddlOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string ddlSmall {
            get {
                return ResourceManager.GetString("ddlSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose championship:.
        /// </summary>
        public static string lbChampSettings {
            get {
                return ResourceManager.GetString("lbChampSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lbCountry {
            get {
                return ResourceManager.GetString("lbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite team.
        /// </summary>
        public static string lbFavTeam {
            get {
                return ResourceManager.GetString("lbFavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA code.
        /// </summary>
        public static string lbFifaCode {
            get {
                return ResourceManager.GetString("lbFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games drawn.
        /// </summary>
        public static string lbGamesDrawn {
            get {
                return ResourceManager.GetString("lbGamesDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games lost.
        /// </summary>
        public static string lbGamesLost {
            get {
                return ResourceManager.GetString("lbGamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played.
        /// </summary>
        public static string lbGamesPlayed {
            get {
                return ResourceManager.GetString("lbGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won.
        /// </summary>
        public static string lbGamesWon {
            get {
                return ResourceManager.GetString("lbGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference.
        /// </summary>
        public static string lbGoalDifference {
            get {
                return ResourceManager.GetString("lbGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals conceded.
        /// </summary>
        public static string lbGoalsConceded {
            get {
                return ResourceManager.GetString("lbGoalsConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored.
        /// </summary>
        public static string lbGoalsScored {
            get {
                return ResourceManager.GetString("lbGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language:.
        /// </summary>
        public static string lbLangSettings {
            get {
                return ResourceManager.GetString("lbLangSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposing team.
        /// </summary>
        public static string lbOpponentTeam {
            get {
                return ResourceManager.GetString("lbOpponentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose screen size:.
        /// </summary>
        public static string lbScreenSizeSettings {
            get {
                return ResourceManager.GetString("lbScreenSizeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string lbWait {
            get {
                return ResourceManager.GetString("lbWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required data could not be loaded..
        /// </summary>
        public static string messageDataUnavaliable {
            get {
                return ResourceManager.GetString("messageDataUnavaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language is not supported. Defaulting to English..
        /// </summary>
        public static string messageDefaultEnglish {
            get {
                return ResourceManager.GetString("messageDefaultEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want these settings?.
        /// </summary>
        public static string messageLangAndChamp {
            get {
                return ResourceManager.GetString("messageLangAndChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the app?.
        /// </summary>
        public static string messageLeaving {
            get {
                return ResourceManager.GetString("messageLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string messageWarning {
            get {
                return ResourceManager.GetString("messageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to championship.
        /// </summary>
        public static string msgMissingChampionship {
            get {
                return ResourceManager.GetString("msgMissingChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string msgMissingLanguage {
            get {
                return ResourceManager.GetString("msgMissingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen size.
        /// </summary>
        public static string msgMissingScreenSize {
            get {
                return ResourceManager.GetString("msgMissingScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following selections are missing: {0}..
        /// </summary>
        public static string msgMissingSelectionsTemplate {
            get {
                return ResourceManager.GetString("msgMissingSelectionsTemplate", resourceCulture);
            }
        }
    }
}
