//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchView.Properties.Resource_de-DE", typeof(Resource_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kroatisch.
        /// </summary>
        public static string ddlCroatian {
            get {
                return ResourceManager.GetString("ddlCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        public static string ddlEnglish {
            get {
                return ResourceManager.GetString("ddlEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frauen.
        /// </summary>
        public static string ddlFemale {
            get {
                return ResourceManager.GetString("ddlFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vollbild.
        /// </summary>
        public static string ddlFullscreen {
            get {
                return ResourceManager.GetString("ddlFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string ddlGerman {
            get {
                return ResourceManager.GetString("ddlGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Männer.
        /// </summary>
        public static string ddlMale {
            get {
                return ResourceManager.GetString("ddlMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string ddlOriginal {
            get {
                return ResourceManager.GetString("ddlOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klein.
        /// </summary>
        public static string ddlSmall {
            get {
                return ResourceManager.GetString("ddlSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie die Meisterschaft:.
        /// </summary>
        public static string lbChampSettings {
            get {
                return ResourceManager.GetString("lbChampSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string lbCountry {
            get {
                return ResourceManager.GetString("lbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieblingsteam.
        /// </summary>
        public static string lbFavTeam {
            get {
                return ResourceManager.GetString("lbFavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA-Code.
        /// </summary>
        public static string lbFifaCode {
            get {
                return ResourceManager.GetString("lbFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unentschiedene Spiele.
        /// </summary>
        public static string lbGamesDrawn {
            get {
                return ResourceManager.GetString("lbGamesDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlorene Spiele.
        /// </summary>
        public static string lbGamesLost {
            get {
                return ResourceManager.GetString("lbGamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiele gespielt.
        /// </summary>
        public static string lbGamesPlayed {
            get {
                return ResourceManager.GetString("lbGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewonnene Spiele.
        /// </summary>
        public static string lbGamesWon {
            get {
                return ResourceManager.GetString("lbGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tordifferenz.
        /// </summary>
        public static string lbGoalDifference {
            get {
                return ResourceManager.GetString("lbGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erhaltene Tore.
        /// </summary>
        public static string lbGoalsConceded {
            get {
                return ResourceManager.GetString("lbGoalsConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzielte Tore.
        /// </summary>
        public static string lbGoalsScored {
            get {
                return ResourceManager.GetString("lbGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie die Sprache:.
        /// </summary>
        public static string lbLangSettings {
            get {
                return ResourceManager.GetString("lbLangSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegnerisches Team.
        /// </summary>
        public static string lbOpponentTeam {
            get {
                return ResourceManager.GetString("lbOpponentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie die Bildschirmgröße:.
        /// </summary>
        public static string lbScreenSizeSettings {
            get {
                return ResourceManager.GetString("lbScreenSizeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wird geladen, bitte warten....
        /// </summary>
        public static string lbWait {
            get {
                return ResourceManager.GetString("lbWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die erforderlichen Daten konnten nicht geladen werden..
        /// </summary>
        public static string messageDataUnavaliable {
            get {
                return ResourceManager.GetString("messageDataUnavaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die ausgewählte Sprache wird nicht unterstützt. Die Standardeinstellung ist Englisch..
        /// </summary>
        public static string messageDefaultEnglish {
            get {
                return ResourceManager.GetString("messageDefaultEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie diese Einstellungen speichern möchten?.
        /// </summary>
        public static string messageLangAndChamp {
            get {
                return ResourceManager.GetString("messageLangAndChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie die App schließen möchten?.
        /// </summary>
        public static string messageLeaving {
            get {
                return ResourceManager.GetString("messageLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        public static string messageWarning {
            get {
                return ResourceManager.GetString("messageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meisterschaft.
        /// </summary>
        public static string msgMissingChampionship {
            get {
                return ResourceManager.GetString("msgMissingChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string msgMissingLanguage {
            get {
                return ResourceManager.GetString("msgMissingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildschirmgröße.
        /// </summary>
        public static string msgMissingScreenSize {
            get {
                return ResourceManager.GetString("msgMissingScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Auswahlmöglichkeiten fehlen: {0}..
        /// </summary>
        public static string msgMissingSelectionsTemplate {
            get {
                return ResourceManager.GetString("msgMissingSelectionsTemplate", resourceCulture);
            }
        }
    }
}
