//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_hr_HR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_hr_HR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballPro.Properties.Resource_hr-HR", typeof(Resource_hr_HR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sliku.
        /// </summary>
        internal static string btnAddPicture {
            get {
                return ResourceManager.GetString("btnAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U redu.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printaj.
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi omiljene igrače.
        /// </summary>
        internal static string btnSaveFavPlayers {
            get {
                return ResourceManager.GetString("btnSaveFavPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi omiljeni tim:.
        /// </summary>
        internal static string btnTeamFav {
            get {
                return ResourceManager.GetString("btnTeamFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrvatski.
        /// </summary>
        internal static string ddlCroatian {
            get {
                return ResourceManager.GetString("ddlCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engleski.
        /// </summary>
        internal static string ddlEnglish {
            get {
                return ResourceManager.GetString("ddlEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to žensko.
        /// </summary>
        internal static string ddlFemale {
            get {
                return ResourceManager.GetString("ddlFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to njemački.
        /// </summary>
        internal static string ddlGerman {
            get {
                return ResourceManager.GetString("ddlGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muško.
        /// </summary>
        internal static string ddlMale {
            get {
                return ResourceManager.GetString("ddlMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi igrači.
        /// </summary>
        internal static string lbAllPlayers {
            get {
                return ResourceManager.GetString("lbAllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi reprezentaciju:.
        /// </summary>
        internal static string lbChampSettings {
            get {
                return ResourceManager.GetString("lbChampSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljeni igrači.
        /// </summary>
        internal static string lbFavPlayers {
            get {
                return ResourceManager.GetString("lbFavPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova.
        /// </summary>
        internal static string lbGoals {
            get {
                return ResourceManager.GetString("lbGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi jezik:.
        /// </summary>
        internal static string lbLangSettings {
            get {
                return ResourceManager.GetString("lbLangSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj posjetitelja.
        /// </summary>
        internal static string lbVisitors {
            get {
                return ResourceManager.GetString("lbVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje, molimo pričekajte....
        /// </summary>
        internal static string lbWait {
            get {
                return ResourceManager.GetString("lbWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih karti.
        /// </summary>
        internal static string lbYellowCards {
            get {
                return ResourceManager.GetString("lbYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste izabrali novu  jezik i reprezentaciju..
        /// </summary>
        internal static string messageChooseLangAndChamp {
            get {
                return ResourceManager.GetString("messageChooseLangAndChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste odabrali omiljeni tim..
        /// </summary>
        internal static string messageFavTeam {
            get {
                return ResourceManager.GetString("messageFavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li ste sigurni da želite postaviti  {0} jezik i {1} reprezentaciju?.
        /// </summary>
        internal static string messageLangAndChamp {
            get {
                return ResourceManager.GetString("messageLangAndChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite zatvoriti aplikaciju?.
        /// </summary>
        internal static string messageLeaving {
            get {
                return ResourceManager.GetString("messageLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string messageWarning {
            get {
                return ResourceManager.GetString("messageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate izabrati tri najdraža igrača..
        /// </summary>
        internal static string messageWarningThreePlayers {
            get {
                return ResourceManager.GetString("messageWarningThreePlayers", resourceCulture);
            }
        }
    }
}
