//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballPro.Properties.Resource_en-US", typeof(Resource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add picture.
        /// </summary>
        public static string btnAddPicture {
            get {
                return ResourceManager.GetString("btnAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save favorite players.
        /// </summary>
        public static string btnSaveFavPlayers {
            get {
                return ResourceManager.GetString("btnSaveFavPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose favourite team:.
        /// </summary>
        public static string btnTeamFav {
            get {
                return ResourceManager.GetString("btnTeamFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string ddlCroatian {
            get {
                return ResourceManager.GetString("ddlCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ddlEnglish {
            get {
                return ResourceManager.GetString("ddlEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string ddlFemale {
            get {
                return ResourceManager.GetString("ddlFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string ddlGerman {
            get {
                return ResourceManager.GetString("ddlGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string ddlMale {
            get {
                return ResourceManager.GetString("ddlMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players.
        /// </summary>
        public static string lbAllPlayers {
            get {
                return ResourceManager.GetString("lbAllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose championship:.
        /// </summary>
        public static string lbChampSettings {
            get {
                return ResourceManager.GetString("lbChampSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite players.
        /// </summary>
        public static string lbFavPlayers {
            get {
                return ResourceManager.GetString("lbFavPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of goals.
        /// </summary>
        public static string lbGoals {
            get {
                return ResourceManager.GetString("lbGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language:.
        /// </summary>
        public static string lbLangSettings {
            get {
                return ResourceManager.GetString("lbLangSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of visitors.
        /// </summary>
        public static string lbVisitors {
            get {
                return ResourceManager.GetString("lbVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string lbWait {
            get {
                return ResourceManager.GetString("lbWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of yellow cards.
        /// </summary>
        public static string lbYellowCards {
            get {
                return ResourceManager.GetString("lbYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a new language or a championship..
        /// </summary>
        public static string messageChooseLangAndChamp {
            get {
                return ResourceManager.GetString("messageChooseLangAndChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not chosen a favorite team..
        /// </summary>
        public static string messageFavTeam {
            get {
                return ResourceManager.GetString("messageFavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set {0} language and  {1} championship?.
        /// </summary>
        public static string messageLangAndChamp {
            get {
                return ResourceManager.GetString("messageLangAndChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the app?.
        /// </summary>
        public static string messageLeaving {
            get {
                return ResourceManager.GetString("messageLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string messageWarning {
            get {
                return ResourceManager.GetString("messageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose three favorite players..
        /// </summary>
        public static string messageWarningThreePlayers {
            get {
                return ResourceManager.GetString("messageWarningThreePlayers", resourceCulture);
            }
        }
    }
}
